[package]
name = "surf-bored"
version = "0.4.2"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
ratatui = "0.29.0"
bored = { path = "../bored"}
tokio = "1.44.2"
serde = "1.0.219"
toml = "0.8.22"
thiserror = "2.0.12"
rand = "0.9.1"
open = "5.3.2"
autonomi = "0.5.3"
