[package]
name = "bored"
version = "0.2.1"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
autonomi = "0.6.3"
bincode = "1.3.3"
blsttc = "8.0.2"
regex = "1.11.1"
serde = {  version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.44.2"
