[package]
name = "bored"
version = "0.1.0"
edition = "2024"

[dependencies]
autonomi = "0.4.5"
bincode = "1.3.3"
regex = "1.11.1"
serde = {  version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.44.2"
